server:
  port: 8001
spring:
  application:
    name: eureka
  security:
    # 用户名密码
    user:
      name: nlp_admin
      password: nlp_admin
eureka:
  client:
    # 是否将自己注册到Eureka Server，默认为true
    register-with-eureka: false
    # 是否从Eureka Server获取注册信息，默认为true
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka
